### ISSUE TITLE
Support for objects in monitoringParameters

### ISSUE THREAD

**Issue by henrikfoss** [SneaksAndData/nexus#12]
I have an algorithm where the payload will always include a country code, which I use for logging and metrics. This is currently implemented as follows:

```
  monitoringParameters:
    - Header.CountryIsoCode
```

However, I now have use cases where I want to monitor an additional parameter in my payload that is optional. I would like to specify a default value for this parameter if it is absent. Ideally, it would look like this:

```
  monitoringParameters:
     - property: Header.CountryIsoCode
     - property: RequestInfo.SolutionType
       default: "MIP"
```

In this setup:

- Header.CountryIsoCode is always expected to be present in the payload.
- If RequestInfo.SolutionType is missing from the payload, the default value "MIP" will be used for monitoring.
